# Jekyll configuration

# Site settings
title: 2016 Annual Report
email: info@loudounchamber.org
description: 2016 Annual Report
baseurl: ''
url: 'http://annualreport.loudounchamber.org'

cdnurl: 'https://d280tyru8g19x6.cloudfront.net'
imgpath: '/assets/img/'
csshash: '-5df93bcda5'
jshash: '-53abea0005'
ganalytics: ''

# Data
company:
  name: Loudoun Chamber of Commerce
  website: http://www.loudounchamber.org
  address: 19301 Winmeade Drive, Suite 210, Lansdowne, VA 20176
  phone: (703) 777-2176

navigation:
  - slug: intro
    title: Introduction
  - slug: engage
    title: Engage
  - slug: advocate
    title: Advocate
  - slug: community
    title: Community
  - slug: awards
    title: Awards
  - slug: board
    title: Board of Directors

# Build settings
markdown: kramdown
include: ['_pages']
exclude: ['package.json', 'node_modules', 'gulpfile.js']

# Posts
permalink: /articles/:year/:month/:title/

collections:
  - sections